"""
Module 7: Signal Tracker

Logs every signal generated by the Oracle and tracks outcomes.
This validates strategy performance on REAL data without risking money.
"""

import logging
import sqlite3
from datetime import datetime, timedelta
from typing import Dict, List, Optional
from pathlib import Path

logger = logging.getLogger(__name__)


class SignalTracker:
    """
    Tracks Oracle signals and their outcomes.

    Logs every signal, monitors market movements, calculates win rates
    and actual edge captured. This is your "paper trading" validation system.
    """

    def __init__(self, db_path: str = "data/oracle_data.db"):
        """
        Initialize signal tracker.

        Args:
            db_path (str): Path to SQLite database
        """
        self.db_path = db_path

        # Ensure data directory exists
        Path(db_path).parent.mkdir(parents=True, exist_ok=True)

        # Initialize database
        self._init_database()

        logger.info("SignalTracker initialized")

    def _init_database(self):
        """Initialize database schema for signals."""
        conn = sqlite3.connect(self.db_path)
        cursor = conn.cursor()

        # Table: signals
        cursor.execute("""
            CREATE TABLE IF NOT EXISTS signals (
                id INTEGER PRIMARY KEY AUTOINCREMENT,
                timestamp DATETIME NOT NULL,
                strategy TEXT NOT NULL,
                market_name TEXT NOT NULL,
                exchange TEXT,
                market_id TEXT,

                signal_type TEXT NOT NULL,
                conviction TEXT,

                fair_value REAL,
                market_price REAL,
                edge_cents REAL,

                entry_price REAL,
                current_price REAL,
                exit_price REAL,

                target_price REAL,
                stop_loss REAL,

                status TEXT DEFAULT 'active',
                outcome TEXT,
                profit_loss REAL,

                rationale TEXT,
                metadata TEXT,

                created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
                updated_at DATETIME DEFAULT CURRENT_TIMESTAMP,
                closed_at DATETIME
            )
        """)

        # Table: signal_updates
        cursor.execute("""
            CREATE TABLE IF NOT EXISTS signal_updates (
                id INTEGER PRIMARY KEY AUTOINCREMENT,
                signal_id INTEGER NOT NULL,
                timestamp DATETIME NOT NULL,
                price REAL NOT NULL,
                action TEXT,
                notes TEXT,
                created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
                FOREIGN KEY (signal_id) REFERENCES signals (id)
            )
        """)

        # Create indices
        cursor.execute("""
            CREATE INDEX IF NOT EXISTS idx_signals_timestamp
            ON signals(timestamp)
        """)

        cursor.execute("""
            CREATE INDEX IF NOT EXISTS idx_signals_strategy
            ON signals(strategy)
        """)

        cursor.execute("""
            CREATE INDEX IF NOT EXISTS idx_signals_status
            ON signals(status)
        """)

        conn.commit()
        conn.close()

    def log_signal(
        self,
        strategy: str,
        market_name: str,
        signal_type: str,
        edge_cents: float,
        conviction: str = "MEDIUM",
        fair_value: Optional[float] = None,
        market_price: Optional[float] = None,
        rationale: Optional[str] = None,
        metadata: Optional[Dict] = None,
        **kwargs
    ) -> int:
        """
        Log a new signal.

        Args:
            strategy (str): Strategy name (e.g., "BiasCorrector", "SpatialArb")
            market_name (str): Market name
            signal_type (str): Signal type (e.g., "BUY", "SELL", "BUY_KALSHI_SELL_POLY")
            edge_cents (float): Calculated edge in cents
            conviction (str): Conviction level
            fair_value (float, optional): Model's fair value
            market_price (float, optional): Current market price
            rationale (str, optional): Signal rationale
            metadata (dict, optional): Additional data
            **kwargs: Additional fields

        Returns:
            int: Signal ID
        """
        conn = sqlite3.connect(self.db_path)
        cursor = conn.cursor()

        # Convert metadata to JSON string if provided
        import json
        metadata_str = json.dumps(metadata) if metadata else None

        cursor.execute("""
            INSERT INTO signals (
                timestamp, strategy, market_name, signal_type, conviction,
                fair_value, market_price, edge_cents, entry_price,
                status, rationale, metadata,
                exchange, market_id, target_price, stop_loss
            ) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
        """, (
            datetime.now(),
            strategy,
            market_name,
            signal_type,
            conviction,
            fair_value,
            market_price,
            edge_cents,
            market_price,  # entry_price = market_price initially
            'active',
            rationale,
            metadata_str,
            kwargs.get('exchange'),
            kwargs.get('market_id'),
            kwargs.get('target_price'),
            kwargs.get('stop_loss')
        ))

        signal_id = cursor.lastrowid
        conn.commit()
        conn.close()

        logger.info(
            f"Signal logged: #{signal_id} | {strategy} | {market_name} | "
            f"{signal_type} | Edge: {edge_cents:+.2f}¢ | Conviction: {conviction}"
        )

        return signal_id

    def update_signal(
        self,
        signal_id: int,
        current_price: Optional[float] = None,
        status: Optional[str] = None,
        outcome: Optional[str] = None,
        profit_loss: Optional[float] = None,
        notes: Optional[str] = None
    ):
        """
        Update an existing signal.

        Args:
            signal_id (int): Signal ID
            current_price (float, optional): Updated price
            status (str, optional): New status ('active', 'closed', 'expired')
            outcome (str, optional): Outcome ('win', 'loss', 'breakeven')
            profit_loss (float, optional): P&L in cents
            notes (str, optional): Update notes
        """
        conn = sqlite3.connect(self.db_path)
        cursor = conn.cursor()

        # Update signal
        updates = []
        values = []

        if current_price is not None:
            updates.append("current_price = ?")
            values.append(current_price)

        if status is not None:
            updates.append("status = ?")
            values.append(status)

        if outcome is not None:
            updates.append("outcome = ?")
            values.append(outcome)

        if profit_loss is not None:
            updates.append("profit_loss = ?")
            values.append(profit_loss)

        if status == 'closed':
            updates.append("closed_at = ?")
            updates.append("exit_price = ?")
            values.append(datetime.now())
            values.append(current_price)

        updates.append("updated_at = ?")
        values.append(datetime.now())

        if updates:
            values.append(signal_id)
            cursor.execute(f"""
                UPDATE signals
                SET {', '.join(updates)}
                WHERE id = ?
            """, values)

        # Log update
        if current_price or notes:
            cursor.execute("""
                INSERT INTO signal_updates (signal_id, timestamp, price, action, notes)
                VALUES (?, ?, ?, ?, ?)
            """, (signal_id, datetime.now(), current_price, status, notes))

        conn.commit()
        conn.close()

        logger.info(f"Signal #{signal_id} updated: status={status}, outcome={outcome}")

    def auto_update_signals_from_market_data(self):
        """
        Automatically update active signals with latest market prices.

        This checks the market_snapshots table and updates current_price
        for all active signals.
        """
        conn = sqlite3.connect(self.db_path)
        cursor = conn.cursor()

        # Get all active signals
        cursor.execute("""
            SELECT id, market_id, exchange, entry_price, signal_type
            FROM signals
            WHERE status = 'active'
        """)

        active_signals = cursor.fetchall()

        updated_count = 0

        for signal_id, market_id, exchange, entry_price, signal_type in active_signals:
            # Get latest price for this market
            cursor.execute("""
                SELECT mid_price
                FROM market_snapshots
                WHERE market_id = ? AND exchange = ?
                ORDER BY timestamp DESC
                LIMIT 1
            """, (market_id, exchange))

            result = cursor.fetchone()

            if result:
                current_price = result[0]

                # Calculate P&L
                if signal_type in ['BUY', 'BUY_KALSHI_SELL_POLY', 'BUY_POLY_SELL_KALSHI']:
                    pnl = (current_price - entry_price) * 100  # cents
                elif signal_type in ['SELL', 'SELL_ALL']:
                    pnl = (entry_price - current_price) * 100  # cents
                else:
                    pnl = 0

                # Determine outcome
                if pnl > 0:
                    outcome = 'winning'
                elif pnl < 0:
                    outcome = 'losing'
                else:
                    outcome = 'breakeven'

                # Update signal
                cursor.execute("""
                    UPDATE signals
                    SET current_price = ?, profit_loss = ?, updated_at = ?
                    WHERE id = ?
                """, (current_price, pnl, datetime.now(), signal_id))

                updated_count += 1

        conn.commit()
        conn.close()

        if updated_count > 0:
            logger.info(f"Auto-updated {updated_count} active signals with latest prices")

        return updated_count

    def close_expired_signals(self, hours: int = 24):
        """
        Close signals that are older than N hours.

        Args:
            hours (int): Auto-close signals older than this
        """
        conn = sqlite3.connect(self.db_path)
        cursor = conn.cursor()

        cutoff = datetime.now() - timedelta(hours=hours)

        cursor.execute("""
            UPDATE signals
            SET status = 'expired', closed_at = ?, updated_at = ?
            WHERE status = 'active' AND timestamp < ?
        """, (datetime.now(), datetime.now(), cutoff))

        expired_count = cursor.rowcount
        conn.commit()
        conn.close()

        if expired_count > 0:
            logger.info(f"Auto-closed {expired_count} expired signals (older than {hours}h)")

        return expired_count

    def get_performance_stats(self, strategy: Optional[str] = None, days: int = 7) -> Dict:
        """
        Calculate performance statistics.

        Args:
            strategy (str, optional): Filter by strategy
            days (int): Look back period

        Returns:
            Dict with performance metrics
        """
        conn = sqlite3.connect(self.db_path)
        cursor = conn.cursor()

        cutoff = datetime.now() - timedelta(days=days)

        # Build query
        where_clause = "WHERE timestamp > ?"
        params = [cutoff]

        if strategy:
            where_clause += " AND strategy = ?"
            params.append(strategy)

        # Total signals
        cursor.execute(f"SELECT COUNT(*) FROM signals {where_clause}", params)
        total_signals = cursor.fetchone()[0]

        # By conviction
        cursor.execute(f"""
            SELECT conviction, COUNT(*)
            FROM signals
            {where_clause}
            GROUP BY conviction
        """, params)
        by_conviction = dict(cursor.fetchall())

        # Closed signals
        cursor.execute(f"""
            SELECT COUNT(*), AVG(profit_loss), SUM(profit_loss)
            FROM signals
            {where_clause} AND status = 'closed'
        """, params)
        closed_data = cursor.fetchone()

        # Win rate
        cursor.execute(f"""
            SELECT
                SUM(CASE WHEN profit_loss > 0 THEN 1 ELSE 0 END) as wins,
                SUM(CASE WHEN profit_loss < 0 THEN 1 ELSE 0 END) as losses,
                COUNT(*) as total
            FROM signals
            {where_clause} AND status = 'closed'
        """, params)
        win_data = cursor.fetchone()

        wins = win_data[0] or 0
        losses = win_data[1] or 0
        total_closed = win_data[2] or 0

        win_rate = (wins / total_closed * 100) if total_closed > 0 else 0

        # Average edge
        cursor.execute(f"""
            SELECT AVG(edge_cents), AVG(ABS(edge_cents))
            FROM signals
            {where_clause}
        """, params)
        edge_data = cursor.fetchone()

        # By strategy
        cursor.execute(f"""
            SELECT strategy, COUNT(*), AVG(edge_cents)
            FROM signals
            {where_clause}
            GROUP BY strategy
            ORDER BY COUNT(*) DESC
        """, params)
        by_strategy = cursor.fetchall()

        conn.close()

        return {
            'total_signals': total_signals,
            'by_conviction': by_conviction,
            'total_closed': total_closed,
            'wins': wins,
            'losses': losses,
            'win_rate': win_rate,
            'avg_pnl_per_signal': closed_data[1] or 0,
            'total_pnl': closed_data[2] or 0,
            'avg_edge': edge_data[0] or 0,
            'avg_abs_edge': edge_data[1] or 0,
            'by_strategy': by_strategy,
            'period_days': days
        }

    def print_performance_report(self, days: int = 7):
        """Print a formatted performance report."""
        stats = self.get_performance_stats(days=days)

        print("\n" + "=" * 80)
        print(f"SIGNAL TRACKER PERFORMANCE REPORT (Last {days} days)")
        print("=" * 80)

        print(f"\n📊 Total Signals: {stats['total_signals']}")

        print(f"\n🎯 By Conviction:")
        for conviction, count in stats['by_conviction'].items():
            pct = count / stats['total_signals'] * 100 if stats['total_signals'] > 0 else 0
            print(f"  {conviction}: {count} ({pct:.1f}%)")

        print(f"\n✅ Closed Signals: {stats['total_closed']}")
        print(f"  Wins: {stats['wins']}")
        print(f"  Losses: {stats['losses']}")
        print(f"  Win Rate: {stats['win_rate']:.1f}%")

        print(f"\n💰 P&L:")
        print(f"  Total: {stats['total_pnl']:+.2f}¢")
        print(f"  Avg per signal: {stats['avg_pnl_per_signal']:+.2f}¢")

        print(f"\n📈 Edge:")
        print(f"  Average: {stats['avg_edge']:+.2f}¢")
        print(f"  Absolute: {stats['avg_abs_edge']:.2f}¢")

        print(f"\n🔧 By Strategy:")
        for strategy, count, avg_edge in stats['by_strategy']:
            print(f"  {strategy}: {count} signals (avg edge: {avg_edge:+.2f}¢)")

        print("\n" + "=" * 80)


# Example usage
if __name__ == "__main__":
    logging.basicConfig(
        level=logging.INFO,
        format='%(asctime)s - %(name)s - %(levelname)s - %(message)s'
    )

    print("=" * 80)
    print("SIGNAL TRACKER - Module 7")
    print("=" * 80)

    tracker = SignalTracker()

    # Log example signals
    print("\n[1] Logging example signals...")

    signal_id_1 = tracker.log_signal(
        strategy="SpatialArbitrage",
        market_name="2028 Presidential Election",
        signal_type="BUY_KALSHI_SELL_POLY",
        edge_cents=3.5,
        conviction="HIGH",
        fair_value=0.55,
        market_price=0.48,
        rationale="Kalshi underpriced by 3.5 cents vs Polymarket",
        exchange="kalshi",
        market_id="PREZ-28"
    )

    signal_id_2 = tracker.log_signal(
        strategy="BiasCorrector",
        market_name="2028 Presidential Election",
        signal_type="BUY",
        edge_cents=7.0,
        conviction="HIGH",
        fair_value=0.55,
        market_price=0.48,
        rationale="Neighbor polls show 5% higher support",
        exchange="kalshi",
        market_id="PREZ-28"
    )

    print(f"✅ Logged signals: #{signal_id_1}, #{signal_id_2}")

    # Update signal
    print("\n[2] Updating signal with current price...")
    tracker.update_signal(signal_id_1, current_price=0.52, notes="Price moved in our favor")

    # Get performance stats
    print("\n[3] Performance statistics:")
    tracker.print_performance_report(days=30)
