"""
Realtime Signal Generator
Event-driven signal generation that triggers on every market update.
"""

import logging
import sqlite3
import time
from datetime import datetime
from typing import Dict, List, Optional
from dataclasses import dataclass

from connectors.data_models import OrderBookData
from config.markets import MarketRegistry

logger = logging.getLogger(__name__)


@dataclass
class Signal:
    """Trading signal generated by strategy."""
    timestamp: datetime
    strategy: str
    market_name: str
    market_ticker: str
    signal_type: str  # 'BUY' or 'SELL'
    edge_cents: float  # Mispricing in cents
    conviction: str  # 'HIGH', 'MEDIUM', 'LOW'
    entry_price: Optional[float] = None
    current_price: Optional[float] = None
    profit_loss: Optional[float] = None
    status: str = 'active'


class RealtimeSignalGenerator:
    """
    Event-driven signal generator.

    Analyzes market updates in real-time and generates signals
    when mispricings are detected.
    """

    def __init__(self, db_path: str = "data/oracle_data.db"):
        """
        Initialize signal generator.

        Args:
            db_path: Path to SQLite database
        """
        self.db_path = db_path
        self.registry = MarketRegistry()

        # Strategy thresholds (tuned by ML optimizer)
        self.bias_correction_threshold = 5.0  # cents
        self.flb_threshold = 3.0
        self.rfr_threshold = 4.0
        self.dutch_book_threshold = 2.0
        self.spatial_arb_threshold = 3.0

        # Signal throttle (prevent spam)
        self.last_signal_time = {}  # market_ticker -> timestamp
        self.signal_cooldown = 5  # seconds between signals for same market

        # Market state tracking
        self.market_state = {}  # market_ticker -> state dict

        logger.info("RealtimeSignalGenerator initialized")

    def process_market_update(self, order_book: OrderBookData) -> List[Signal]:
        """
        Process market update and generate signals if edge detected.

        Args:
            order_book: Latest orderbook data

        Returns:
            List of signals (empty if no edge found)
        """
        signals = []

        # Throttle check
        if not self._should_generate_signal(order_book.market_id):
            return signals

        # Update market state
        self._update_market_state(order_book)

        # Run all strategies
        try:
            # Strategy 1: Bias Correction
            bias_signal = self._detect_bias_correction(order_book)
            if bias_signal:
                signals.append(bias_signal)

            # Strategy 2: False Liquidity Bait
            flb_signal = self._detect_false_liquidity_bait(order_book)
            if flb_signal:
                signals.append(flb_signal)

            # Strategy 3: Reversion from Resistance
            rfr_signal = self._detect_reversion_from_resistance(order_book)
            if rfr_signal:
                signals.append(rfr_signal)

            # Strategy 4: Dutch Book Arbitrage
            # (Requires multiple markets - processed separately)

            # Strategy 5: Spatial Arbitrage
            # (Requires Polymarket data - processed separately)

        except Exception as e:
            logger.error(f"Error generating signals for {order_book.market_id}: {e}")

        # Save signals to database
        if signals:
            self._save_signals(signals)
            logger.info(f"🎯 Generated {len(signals)} signals for {order_book.market_name}")

        return signals

    def _should_generate_signal(self, market_ticker: str) -> bool:
        """Check if enough time has passed since last signal."""
        last_time = self.last_signal_time.get(market_ticker, 0)
        current_time = time.time()

        if current_time - last_time < self.signal_cooldown:
            return False

        self.last_signal_time[market_ticker] = current_time
        return True

    def _update_market_state(self, order_book: OrderBookData):
        """Update tracked state for market."""
        market_id = order_book.market_id

        if market_id not in self.market_state:
            self.market_state[market_id] = {
                'price_history': [],
                'spread_history': [],
                'volume_history': [],
                'last_update': None
            }

        state = self.market_state[market_id]

        # Add to histories (keep last 100 points)
        state['price_history'].append(order_book.mid_price)
        state['spread_history'].append(order_book.spread)
        state['volume_history'].append(order_book.bid_size + order_book.ask_size)

        # Trim histories
        if len(state['price_history']) > 100:
            state['price_history'] = state['price_history'][-100:]
            state['spread_history'] = state['spread_history'][-100:]
            state['volume_history'] = state['volume_history'][-100:]

        state['last_update'] = datetime.now()

    def _detect_bias_correction(self, order_book: OrderBookData) -> Optional[Signal]:
        """
        Strategy 1: Bias Correction
        Detects when market price deviates from fair value.
        """
        market_id = order_book.market_id
        state = self.market_state.get(market_id)

        if not state or len(state['price_history']) < 20:
            return None  # Need more data

        # Calculate fair value (simple moving average)
        recent_prices = state['price_history'][-20:]
        fair_value = sum(recent_prices) / len(recent_prices)

        current_price = order_book.mid_price

        # Check for mispricing
        edge_cents = abs(current_price - fair_value) * 100

        if edge_cents > self.bias_correction_threshold:
            # Determine signal type
            if current_price > fair_value:
                signal_type = 'SELL'  # Overpriced
            else:
                signal_type = 'BUY'  # Underpriced

            # Determine conviction
            if edge_cents > 8.0:
                conviction = 'HIGH'
            elif edge_cents > 5.0:
                conviction = 'MEDIUM'
            else:
                conviction = 'LOW'

            return Signal(
                timestamp=datetime.now(),
                strategy='Bias Correction',
                market_name=order_book.market_name,
                market_ticker=market_id,
                signal_type=signal_type,
                edge_cents=edge_cents,
                conviction=conviction,
                entry_price=current_price
            )

        return None

    def _detect_false_liquidity_bait(self, order_book: OrderBookData) -> Optional[Signal]:
        """
        Strategy 2: False Liquidity Bait
        Detects fake walls / liquidity traps.
        """
        market_id = order_book.market_id
        state = self.market_state.get(market_id)

        if not state or len(state['volume_history']) < 10:
            return None

        # Check for sudden volume spike (potential fake wall)
        recent_volume = state['volume_history'][-10:]
        avg_volume = sum(recent_volume[:-1]) / (len(recent_volume) - 1)
        current_volume = recent_volume[-1]

        # Volume spike > 3x average
        if current_volume > avg_volume * 3:
            # Check if spread is narrowing (sign of manipulation)
            recent_spreads = state['spread_history'][-5:]
            if len(recent_spreads) > 1:
                spread_trend = recent_spreads[-1] - recent_spreads[0]

                if spread_trend < 0:  # Spread tightening
                    edge_cents = (order_book.spread * 100) * 2  # Estimate edge

                    if edge_cents > self.flb_threshold:
                        return Signal(
                            timestamp=datetime.now(),
                            strategy='False Liquidity Bait',
                            market_name=order_book.market_name,
                            market_ticker=market_id,
                            signal_type='SELL',  # Fade the manipulation
                            edge_cents=edge_cents,
                            conviction='MEDIUM',
                            entry_price=order_book.mid_price
                        )

        return None

    def _detect_reversion_from_resistance(self, order_book: OrderBookData) -> Optional[Signal]:
        """
        Strategy 3: Reversion from Resistance
        Detects mean reversion opportunities at key price levels.
        """
        market_id = order_book.market_id
        state = self.market_state.get(market_id)

        if not state or len(state['price_history']) < 30:
            return None

        prices = state['price_history']
        current_price = order_book.mid_price

        # Find local max/min (resistance/support)
        recent_max = max(prices[-20:])
        recent_min = min(prices[-20:])

        # Check if price near resistance (top 5%)
        if current_price > recent_max * 0.95:
            # Check momentum (volume declining = exhaustion)
            if len(state['volume_history']) > 5:
                recent_vol = state['volume_history'][-5:]
                if recent_vol[-1] < recent_vol[0]:  # Volume declining

                    # Calculate edge
                    mean_price = sum(prices[-20:]) / 20
                    edge_cents = (current_price - mean_price) * 100

                    if edge_cents > self.rfr_threshold:
                        return Signal(
                            timestamp=datetime.now(),
                            strategy='Reversion from Resistance',
                            market_name=order_book.market_name,
                            market_ticker=market_id,
                            signal_type='SELL',  # Expect reversion down
                            edge_cents=edge_cents,
                            conviction='HIGH' if edge_cents > 6 else 'MEDIUM',
                            entry_price=current_price
                        )

        # Check if price near support (bottom 5%)
        elif current_price < recent_min * 1.05:
            if len(state['volume_history']) > 5:
                recent_vol = state['volume_history'][-5:]
                if recent_vol[-1] < recent_vol[0]:

                    mean_price = sum(prices[-20:]) / 20
                    edge_cents = (mean_price - current_price) * 100

                    if edge_cents > self.rfr_threshold:
                        return Signal(
                            timestamp=datetime.now(),
                            strategy='Reversion from Resistance',
                            market_name=order_book.market_name,
                            market_ticker=market_id,
                            signal_type='BUY',  # Expect reversion up
                            edge_cents=edge_cents,
                            conviction='HIGH' if edge_cents > 6 else 'MEDIUM',
                            entry_price=current_price
                        )

        return None

    def _save_signals(self, signals: List[Signal]):
        """Save signals to database."""
        conn = sqlite3.connect(self.db_path)
        cursor = conn.cursor()

        for signal in signals:
            cursor.execute("""
                INSERT INTO signals (
                    timestamp, strategy, market_name, market_id,
                    signal_type, edge_cents, conviction,
                    entry_price, current_price, profit_loss, status
                ) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
            """, (
                signal.timestamp,
                signal.strategy,
                signal.market_name,
                signal.market_ticker,
                signal.signal_type,
                signal.edge_cents,
                signal.conviction,
                signal.entry_price,
                signal.current_price,
                signal.profit_loss,
                signal.status
            ))

        conn.commit()
        conn.close()

    def update_strategy_thresholds(self, thresholds: Dict[str, float]):
        """
        Update strategy thresholds (called by ML optimizer).

        Args:
            thresholds: Dict of strategy name -> threshold value
        """
        self.bias_correction_threshold = thresholds.get('bias_correction', self.bias_correction_threshold)
        self.flb_threshold = thresholds.get('flb', self.flb_threshold)
        self.rfr_threshold = thresholds.get('rfr', self.rfr_threshold)
        self.dutch_book_threshold = thresholds.get('dutch_book', self.dutch_book_threshold)
        self.spatial_arb_threshold = thresholds.get('spatial_arb', self.spatial_arb_threshold)

        logger.info(f"Strategy thresholds updated: {thresholds}")
