import { Card } from '@/types';

export const sampleCards: Card[] = [
  {
    id: '1',
    title: '1997-98 Metal Universe Precious Metal Gems',
    player: 'Michael Jordan',
    year: 1997,
    sport: 'basketball',
    set: 'Metal Universe PMG',
    cardNumber: '23',
    condition: 'mint',
    graded: true,
    grade: 9.5,
    gradingCompany: 'BGS',
    price: 125000,
    imageUrl: '/cards/jordan.jpg',
    sellerId: 'seller1',
    sellerName: 'CardKing',
    sellerRating: 4.9,
    description: 'Extremely rare PSA 10. One of only 10 in existence.',
    category: 'Basketball',
    era: '1990s',
    featured: true,
  },
  {
    id: '2',
    title: '2003-04 Topps Chrome Refractor',
    player: 'LeBron James',
    year: 2003,
    sport: 'basketball',
    set: 'Topps Chrome',
    cardNumber: '111',
    condition: 'near-mint',
    graded: true,
    grade: 9,
    gradingCompany: 'PSA',
    price: 45000,
    imageUrl: '/cards/lebron.jpg',
    sellerId: 'seller2',
    sellerName: 'ProCollector',
    sellerRating: 4.8,
    description: 'LeBron James rookie card. Beautiful centering.',
    category: 'Basketball',
    era: '2000s',
    featured: true,
  },
  {
    id: '3',
    title: '1952 Topps Baseball',
    player: 'Mickey Mantle',
    year: 1952,
    sport: 'baseball',
    set: 'Topps',
    cardNumber: '311',
    condition: 'excellent',
    graded: true,
    grade: 8,
    gradingCompany: 'PSA',
    price: 850000,
    imageUrl: '/cards/mantle.jpg',
    sellerId: 'seller3',
    sellerName: 'VintageCards',
    sellerRating: 5.0,
    description: 'The holy grail of baseball cards. PSA 8.',
    category: 'Baseball',
    era: 'Vintage',
    featured: true,
  },
  {
    id: '4',
    title: '2017-18 Panini National Treasures',
    player: 'Giannis Antetokounmpo',
    year: 2017,
    sport: 'basketball',
    set: 'National Treasures',
    cardNumber: '125',
    condition: 'mint',
    graded: true,
    grade: 10,
    gradingCompany: 'PSA',
    price: 12000,
    imageUrl: '/cards/giannis.jpg',
    sellerId: 'seller4',
    sellerName: 'ModernCards',
    sellerRating: 4.7,
    description: 'Autographed patch card. Numbered to 99.',
    category: 'Basketball',
    era: '2010s',
  },
  {
    id: '5',
    title: '1986 Fleer Basketball',
    player: 'Michael Jordan',
    year: 1986,
    sport: 'basketball',
    set: 'Fleer',
    cardNumber: '57',
    condition: 'mint',
    graded: true,
    grade: 10,
    gradingCompany: 'PSA',
    price: 225000,
    imageUrl: '/cards/jordan86.jpg',
    sellerId: 'seller1',
    sellerName: 'CardKing',
    sellerRating: 4.9,
    description: 'Jordan rookie card. PSA 10 gem mint.',
    category: 'Basketball',
    era: '1980s',
    featured: true,
  },
  {
    id: '6',
    title: '2018 Panini Prizm',
    player: 'Luka Doncic',
    year: 2018,
    sport: 'basketball',
    set: 'Prizm',
    cardNumber: '280',
    condition: 'mint',
    graded: true,
    grade: 10,
    gradingCompany: 'PSA',
    price: 8500,
    imageUrl: '/cards/luka.jpg',
    sellerId: 'seller5',
    sellerName: 'RookieCards',
    sellerRating: 4.9,
    description: 'Silver Prizm refractor. Population of 150.',
    category: 'Basketball',
    era: '2010s',
  },
  {
    id: '7',
    title: '1989 Upper Deck',
    player: 'Ken Griffey Jr.',
    year: 1989,
    sport: 'baseball',
    set: 'Upper Deck',
    cardNumber: '1',
    condition: 'near-mint',
    graded: true,
    grade: 9,
    gradingCompany: 'PSA',
    price: 1200,
    imageUrl: '/cards/griffey.jpg',
    sellerId: 'seller6',
    sellerName: 'BaseballPro',
    sellerRating: 4.8,
    description: 'Iconic rookie card in excellent condition.',
    category: 'Baseball',
    era: '1980s',
  },
  {
    id: '8',
    title: '2000 Playoff Contenders',
    player: 'Tom Brady',
    year: 2000,
    sport: 'football',
    set: 'Playoff Contenders',
    cardNumber: '144',
    condition: 'mint',
    graded: true,
    grade: 10,
    gradingCompany: 'PSA',
    price: 175000,
    imageUrl: '/cards/brady.jpg',
    sellerId: 'seller7',
    sellerName: 'FootballCards',
    sellerRating: 4.9,
    description: 'Tom Brady autographed rookie. PSA 10.',
    category: 'Football',
    era: '2000s',
    featured: true,
  },
  {
    id: '9',
    title: '2009-10 Bowman Chrome',
    player: 'Stephen Curry',
    year: 2009,
    sport: 'basketball',
    set: 'Bowman Chrome',
    cardNumber: '110',
    condition: 'mint',
    graded: true,
    grade: 9.5,
    gradingCompany: 'BGS',
    price: 15000,
    imageUrl: '/cards/curry.jpg',
    sellerId: 'seller2',
    sellerName: 'ProCollector',
    sellerRating: 4.8,
    description: 'Refractor autograph. BGS 9.5 gem mint.',
    category: 'Basketball',
    era: '2000s',
  },
  {
    id: '10',
    title: '2019 Panini Prizm',
    player: 'Zion Williamson',
    year: 2019,
    sport: 'basketball',
    set: 'Prizm',
    cardNumber: '248',
    condition: 'mint',
    graded: false,
    price: 450,
    imageUrl: '/cards/zion.jpg',
    sellerId: 'seller5',
    sellerName: 'RookieCards',
    sellerRating: 4.9,
    description: 'Base rookie card. Potential grading candidate.',
    category: 'Basketball',
    era: '2010s',
  },
];
