[package]
name = "ore-solver-ffi"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
ore-common = { path = "../ore-common" }
libc.workspace = true
thiserror.workspace = true
tracing.workspace = true

[build-dependencies]
cc = "1.0"

[lib]
name = "ore_solver_ffi"
crate-type = ["lib", "cdylib"]
